# Generated by Django 5.2 on 2025-05-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_link',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Ссылка на оплату Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус платежа в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сессии в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счёт'), ('stripe', 'Stripe')], max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
