events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name 51.250.99.83;

        root /usr/share/nginx/html;
        index index.html;

        location = /favicon.ico {
            access_log off;
            log_not_found off;
            }

        location /static/ {
            alias /opt/your_project/static/;
            }

        location /media/ {
            alias /opt/your_project/media/;
            }

        location / {
            include proxy_params;
            proxy_pass http://django;
            }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}