# Generated by Django 5.2 on 2025-05-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_subscription_options_alter_subscription_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='title',
        ),
    ]
