# Generated by Django 5.2 on 2025-05-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_rename_title_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='name',
        ),
    ]
