# Generated by Django 5.2 on 2025-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
